name: Release

on:
  create:
    tags:
      - v*
    branches: [stage]

jobs:

  linux-windows-build:
    name: Linux & Windows Build
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:

    - name: Go 1.17
      uses: actions/setup-go@v2
      with:
        go-version: '^1.17'
    
    - name: OS Packages 
      run: |
        sudo apt-get update --fix-missing && sudo apt-get -y install \
        git build-essential zlib1g zlib1g-dev wget zip unzip \
        mingw-w64 binutils-mingw-w64 g++-mingw-w64 gcc-multilib

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        ref: stage

    - name: Git Fetch Tags
      run: git fetch --prune --unshallow --tags -f

    - name: Go Assets
      run: ./go-assets.sh

    - name: Make
      run: export PATH=/home/runner/go/bin/:$PATH && make linux
  
    - name: Linux Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: linux
        path: ./sliver-*

    - name: Make Windows
      run: export PATH=/home/runner/go/bin/:$PATH && make windows

    - name: Windows Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: windows
        path:  ./sliver-*

  macos-build:
    name: MacOS Build
    runs-on: macos-latest
    timeout-minutes: 45
    steps:

    - name: Go 1.17
      uses: actions/setup-go@v2
      with:
        go-version: '^1.17'

    - name: Mingw
      run: brew install mingw-w64

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Git Fetch Tags
      run: git fetch --prune --unshallow --tags -f

    - name: Go Assets
      run: ./go-assets.sh

    - name: Make AMD64
      run: make macos
    
    # - name: Make ARM64
    #   run: make macos-arm64

    - name: MacOS Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: macos
        path: ./sliver-*

  tagged-release:

    needs: [linux-windows-build, macos-build]

    name: "Tagged Release"
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
    - run: mkdir -p ./release && mkdir -p ./artifacts
    - uses: actions/download-artifact@v2
      with:
        path: ./artifacts

    - name: Release
      run: mkdir -p ./release

    # Linux
    - name: Linux AMD64
      run: |
        zip -j ./release/sliver-server_linux.zip ./artifacts/linux/sliver-server
        zip -j ./release/sliver-client_linux.zip ./artifacts/linux/sliver-client

    # Windows
    - name: Windows AMD64
      run: |
        zip -j ./release/sliver-server_windows.zip ./artifacts/windows/sliver-server.exe
        zip -j ./release/sliver-client_windows.zip ./artifacts/windows/sliver-client.exe

    # MacOS AMD64
    - name: MacOS AMD64
      run: |
        zip -j ./release/sliver-server_macos.zip ./artifacts/macos/sliver-server
        zip -j ./release/sliver-client_macos.zip ./artifacts/macos/sliver-client

    # MacOS ARM64
    # - name: Package MacOS ARM64
    #   run: |
    #     zip -j ./release/sliver-server_macos-arm64.zip ./artifacts/macos/sliver-server_arm64
    #     zip -j ./release/sliver-client_macos-arm64.zip ./artifacts/macos/sliver-client_arm64

    - name: "Publish Release"
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        automatic_release_tag: "latest"
        files: |
          ./release/*
